# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sqlite-Users' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sqlite-Users
	pod 'SQLite.swift', '~> 0.13.3'
end
